import { Stock, Transaction, Payout, UserSettings } from "./types";

export const initialStocks: Stock[] = [
  {
    symbol: "O",
    name: "Realty Income Corp",
    sector: "Real Estate",
    price: 54.28,
    yield: 5.64,
    growth5y: 4.2,
    payoutRatio: 74.2,
    frequency: "Monthly",
    historySparkline: [40, 55, 50, 70, 85, 100],
    marketCap: "47.1B",
    pAffo: "13.2x",
    exDivDate: "Oct 31, 2024",
    payDate: "Nov 15, 2024",
    divType: "Qualified",
    safetyScore: 92,
    safetyLabel: "Very Safe",
    whyPick: "Extremely resilient portfolio of triple-net leased properties providing predictable cash flows even in high-interest environments.",
    rank: "01",
    dividendGrowthHistory: [
      { year: 2014, payout: 2.18 },
      { year: 2015, payout: 2.27 },
      { year: 2016, payout: 2.39 },
      { year: 2017, payout: 2.51 },
      { year: 2018, payout: 2.62 },
      { year: 2019, payout: 2.73 },
      { year: 2020, payout: 2.80 },
      { year: 2021, payout: 2.88 },
      { year: 2022, payout: 2.97 },
      { year: 2023, payout: 3.07 }
    ]
  },
  {
    symbol: "AVGO",
    name: "Broadcom Inc.",
    sector: "Technology",
    price: 1284.15,
    yield: 1.62,
    growth5y: 18.5,
    payoutRatio: 44.0,
    frequency: "Quarterly",
    historySparkline: [20, 35, 55, 70, 85, 100],
    marketCap: "598.4B",
    pAffo: "28.4x",
    exDivDate: "Dec 18, 2024",
    payDate: "Dec 30, 2024",
    divType: "Qualified",
    safetyScore: 85,
    safetyLabel: "Very Safe",
    whyPick: "Aggressive dividend hikes backed by robust free cash flow margins from enterprise software and AI networking demands.",
    rank: "02",
    dividendGrowthHistory: [
      { year: 2014, payout: 1.20 },
      { year: 2016, payout: 4.10 },
      { year: 2018, payout: 7.00 },
      { year: 2020, payout: 13.00 },
      { year: 2022, payout: 16.40 },
      { year: 2023, payout: 21.00 }
    ]
  },
  {
    symbol: "PEP",
    name: "PepsiCo, Inc.",
    sector: "Consumer Staples",
    price: 171.88,
    yield: 3.01,
    growth5y: 6.8,
    payoutRatio: 62.0,
    frequency: "Quarterly",
    historySparkline: [60, 65, 75, 80, 90, 100],
    marketCap: "235.8B",
    pAffo: "22.1x",
    exDivDate: "Nov 29, 2024",
    payDate: "Jan 07, 2025",
    divType: "Qualified",
    safetyScore: 88,
    safetyLabel: "Very Safe",
    whyPick: "Dividend Aristocrat with more than 50 years of consecutive dividend growth, supported by a highly diversified snacks and beverage empire.",
    rank: "03",
    dividendGrowthHistory: [
      { year: 2014, payout: 2.55 },
      { year: 2016, payout: 3.02 },
      { year: 2018, payout: 3.59 },
      { year: 2020, payout: 4.02 },
      { year: 2022, payout: 4.60 },
      { year: 2023, payout: 5.06 }
    ]
  },
  {
    symbol: "V",
    name: "Visa Inc.",
    sector: "Financials",
    price: 278.41,
    yield: 0.75,
    growth5y: 15.2,
    payoutRatio: 21.0,
    frequency: "Quarterly",
    historySparkline: [30, 45, 60, 75, 90, 100],
    marketCap: "560.2B",
    pAffo: "26.5x",
    exDivDate: "Nov 08, 2024",
    payDate: "Dec 03, 2024",
    divType: "Qualified",
    safetyScore: 98,
    safetyLabel: "Very Safe",
    whyPick: "Ultra-low payout ratio and unmatched digital transaction monopoly leave massive room for continued double-digit dividend growth.",
    rank: "04",
    dividendGrowthHistory: [
      { year: 2014, payout: 0.40 },
      { year: 2016, payout: 0.56 },
      { year: 2018, payout: 0.84 },
      { year: 2020, payout: 1.20 },
      { year: 2022, payout: 1.50 },
      { year: 2023, payout: 2.08 }
    ]
  },
  {
    symbol: "MAIN",
    name: "Main Street Capital",
    sector: "Financials",
    price: 48.50,
    yield: 6.45,
    growth5y: 5.8,
    payoutRatio: 82.0,
    frequency: "Monthly",
    historySparkline: [50, 60, 55, 75, 80, 100],
    marketCap: "3.9B",
    pAffo: "9.8x",
    exDivDate: "Nov 20, 2024",
    payDate: "Dec 15, 2024",
    divType: "Ordinary",
    safetyScore: 78,
    safetyLabel: "Safe",
    whyPick: "Strong BDC fundamentals with consistent supplemental dividends and conservative underwriting in the lower middle market.",
    rank: "02",
    dividendGrowthHistory: [
      { year: 2014, payout: 1.98 },
      { year: 2016, payout: 2.16 },
      { year: 2018, payout: 2.28 },
      { year: 2020, payout: 2.46 },
      { year: 2022, payout: 2.62 },
      { year: 2023, payout: 2.88 }
    ]
  },
  {
    symbol: "STAG",
    name: "STAG Industrial",
    sector: "Real Estate",
    price: 36.80,
    yield: 4.12,
    growth5y: 2.1,
    payoutRatio: 68.0,
    frequency: "Monthly",
    historySparkline: [30, 40, 50, 65, 80, 100],
    marketCap: "6.7B",
    pAffo: "16.1x",
    exDivDate: "Oct 31, 2024",
    payDate: "Nov 15, 2024",
    divType: "Qualified",
    safetyScore: 82,
    safetyLabel: "Safe",
    whyPick: "Focus on single-tenant industrial properties with exposure to growing e-commerce logistics and light manufacturing.",
    rank: "03",
    dividendGrowthHistory: [
      { year: 2014, payout: 1.35 },
      { year: 2016, payout: 1.39 },
      { year: 2018, payout: 1.42 },
      { year: 2020, payout: 1.44 },
      { year: 2022, payout: 1.46 },
      { year: 2023, payout: 1.48 }
    ]
  },
  {
    symbol: "ADC",
    name: "Agree Realty",
    sector: "Real Estate",
    price: 61.20,
    yield: 4.88,
    growth5y: 6.1,
    payoutRatio: 72.0,
    frequency: "Monthly",
    historySparkline: [40, 48, 55, 70, 85, 100],
    marketCap: "6.1B",
    pAffo: "15.4x",
    exDivDate: "Oct 31, 2024",
    payDate: "Nov 14, 2024",
    divType: "Qualified",
    safetyScore: 86,
    safetyLabel: "Safe",
    whyPick: "High-quality retail tenant base and a strong balance sheet supporting monthly compounding dividends and defensive market positioning.",
    rank: "04",
    dividendGrowthHistory: [
      { year: 2014, payout: 1.70 },
      { year: 2016, payout: 1.92 },
      { year: 2018, payout: 2.18 },
      { year: 2020, payout: 2.42 },
      { year: 2022, payout: 2.76 },
      { year: 2023, payout: 2.96 }
    ]
  },
  {
    symbol: "LTC",
    name: "LTC Properties",
    sector: "Real Estate",
    price: 32.85,
    yield: 6.95,
    growth5y: 1.8,
    payoutRatio: 88.0,
    frequency: "Monthly",
    historySparkline: [20, 40, 50, 70, 80, 100],
    marketCap: "1.4B",
    pAffo: "12.8x",
    exDivDate: "Nov 21, 2024",
    payDate: "Nov 29, 2024",
    divType: "Qualified",
    safetyScore: 71,
    safetyLabel: "Safe",
    whyPick: "Senior housing and healthcare exposure with stable long-term leases and consistent yield to capture demographic tailwinds.",
    rank: "05",
    dividendGrowthHistory: [
      { year: 2014, payout: 2.04 },
      { year: 2016, payout: 2.16 },
      { year: 2018, payout: 2.28 },
      { year: 2020, payout: 2.28 },
      { year: 2022, payout: 2.28 },
      { year: 2023, payout: 2.28 }
    ]
  },
  {
    symbol: "BRMK",
    name: "Broadmark Realty",
    sector: "Financials",
    price: 10.25,
    yield: 8.20,
    growth5y: 0.5,
    payoutRatio: 90.0,
    frequency: "Monthly",
    historySparkline: [80, 75, 70, 85, 90, 100],
    marketCap: "1.3B",
    pAffo: "11.1x",
    exDivDate: "Sep 28, 2024",
    payDate: "Oct 15, 2024",
    divType: "Ordinary",
    safetyScore: 55,
    safetyLabel: "Borderline",
    whyPick: "Short-term construction lending provides high income with unique market positioning, albeit with higher underlying cycle risks.",
    rank: "06",
    dividendGrowthHistory: [
      { year: 2019, payout: 0.96 },
      { year: 2020, payout: 0.84 },
      { year: 2021, payout: 0.84 },
      { year: 2022, payout: 0.84 },
      { year: 2023, payout: 0.84 }
    ]
  },
  {
    symbol: "EPR",
    name: "EPR Properties",
    sector: "Real Estate",
    price: 43.80,
    yield: 7.54,
    growth5y: 4.8,
    payoutRatio: 84.0,
    frequency: "Monthly",
    historySparkline: [50, 45, 60, 75, 90, 100],
    marketCap: "3.3B",
    pAffo: "10.4x",
    exDivDate: "Oct 30, 2024",
    payDate: "Nov 15, 2024",
    divType: "Qualified",
    safetyScore: 74,
    safetyLabel: "Safe",
    whyPick: "Experiential real estate recovery play with strong dividend coverage and theater rental stability amidst rising social entertainment spend.",
    rank: "07",
    dividendGrowthHistory: [
      { year: 2014, payout: 3.16 },
      { year: 2016, payout: 3.84 },
      { year: 2018, payout: 4.32 },
      { year: 2020, payout: 1.50 },
      { year: 2022, payout: 3.30 },
      { year: 2023, payout: 3.30 }
    ]
  },
  {
    symbol: "GNL",
    name: "Global Net Lease",
    sector: "Real Estate",
    price: 15.48,
    yield: 9.30,
    growth5y: -1.5,
    payoutRatio: 94.0,
    frequency: "Quarterly",
    historySparkline: [60, 50, 55, 70, 85, 100],
    marketCap: "1.6B",
    pAffo: "8.5x",
    exDivDate: "Oct 12, 2024",
    payDate: "Nov 15, 2024",
    divType: "Qualified",
    safetyScore: 48,
    safetyLabel: "Risky",
    whyPick: "Highly diversified international portfolio with long-term locked-in rental income, balancing high yields with structural leverage concerns.",
    rank: "08",
    dividendGrowthHistory: [
      { year: 2015, payout: 2.10 },
      { year: 2017, payout: 1.78 },
      { year: 2019, payout: 1.78 },
      { year: 2021, payout: 1.60 },
      { year: 2023, payout: 1.44 }
    ]
  },
  {
    symbol: "LAND",
    name: "Gladstone Land",
    sector: "Real Estate",
    price: 19.70,
    yield: 2.80,
    growth5y: 5.2,
    payoutRatio: 80.0,
    frequency: "Monthly",
    historySparkline: [40, 50, 60, 75, 85, 100],
    marketCap: "0.7B",
    pAffo: "18.2x",
    exDivDate: "Oct 21, 2024",
    payDate: "Nov 14, 2024",
    divType: "Qualified",
    safetyScore: 84,
    safetyLabel: "Safe",
    whyPick: "Farmland asset appreciation combined with monthly income; a hedge against global inflation with triple-A tenant farming leases.",
    rank: "09",
    dividendGrowthHistory: [
      { year: 2014, payout: 0.42 },
      { year: 2016, payout: 0.49 },
      { year: 2018, payout: 0.52 },
      { year: 2020, payout: 0.54 },
      { year: 2022, payout: 0.55 },
      { year: 2023, payout: 0.55 }
    ]
  },
  {
    symbol: "PBA",
    name: "Pembina Pipeline",
    sector: "Energy",
    price: 35.60,
    yield: 5.40,
    growth5y: 3.5,
    payoutRatio: 72.0,
    frequency: "Quarterly",
    historySparkline: [20, 45, 60, 70, 85, 100],
    marketCap: "19.8B",
    pAffo: "11.5x",
    exDivDate: "Sep 25, 2024",
    payDate: "Oct 15, 2024",
    divType: "Qualified",
    safetyScore: 80,
    safetyLabel: "Safe",
    whyPick: "Critical energy infrastructure with fee-based contracts ensuring payout reliability and insulation from direct commodity price swings.",
    rank: "10",
    dividendGrowthHistory: [
      { year: 2014, payout: 1.74 },
      { year: 2016, payout: 1.92 },
      { year: 2018, payout: 2.28 },
      { year: 2020, payout: 2.52 },
      { year: 2022, payout: 2.64 },
      { year: 2023, payout: 2.64 }
    ]
  },
  {
    symbol: "ARCC",
    name: "Ares Capital",
    sector: "Financials",
    price: 20.50,
    yield: 9.80,
    growth5y: 4.5,
    payoutRatio: 85.0,
    frequency: "Quarterly",
    historySparkline: [50, 60, 55, 75, 80, 100],
    marketCap: "11.2B",
    pAffo: "9.2x",
    exDivDate: "Dec 14, 2024",
    payDate: "Dec 29, 2024",
    divType: "Ordinary",
    safetyScore: 72,
    safetyLabel: "Safe",
    whyPick: "Largest BDC with an excellent track record of navigating credit cycles while maintaining a massive yield.",
    rank: "11",
    dividendGrowthHistory: [
      { year: 2021, payout: 1.64 },
      { year: 2022, payout: 1.76 },
      { year: 2023, payout: 1.92 }
    ]
  },
  {
    symbol: "MO",
    name: "Altria Group",
    sector: "Consumer Staples",
    price: 45.20,
    yield: 8.50,
    growth5y: 4.2,
    payoutRatio: 78.0,
    frequency: "Quarterly",
    historySparkline: [70, 75, 80, 85, 95, 100],
    marketCap: "78.4B",
    pAffo: "9.5x",
    exDivDate: "Dec 20, 2024",
    payDate: "Jan 10, 2025",
    divType: "Qualified",
    safetyScore: 75,
    safetyLabel: "Safe",
    whyPick: "High-yield consumer defensive play with pricing power, aggressively buying back shares while raising dividends.",
    rank: "12",
    dividendGrowthHistory: [
      { year: 2021, payout: 3.44 },
      { year: 2022, payout: 3.60 },
      { year: 2023, payout: 3.76 }
    ]
  },
  {
    symbol: "VZ",
    name: "Verizon Communications",
    sector: "Communication",
    price: 39.80,
    yield: 6.70,
    growth5y: 2.1,
    payoutRatio: 54.0,
    frequency: "Quarterly",
    historySparkline: [50, 60, 70, 80, 90, 100],
    marketCap: "167.3B",
    pAffo: "8.2x",
    exDivDate: "Jan 09, 2025",
    payDate: "Feb 01, 2025",
    divType: "Qualified",
    safetyScore: 82,
    safetyLabel: "Safe",
    whyPick: "Stable telecom giant generating massive free cash flow to easily cover its near 7% yield.",
    rank: "13",
    dividendGrowthHistory: [
      { year: 2021, payout: 2.51 },
      { year: 2022, payout: 2.56 },
      { year: 2023, payout: 2.61 }
    ]
  },
  {
    symbol: "T",
    name: "AT&T Inc.",
    sector: "Communication",
    price: 17.50,
    yield: 6.50,
    growth5y: -2.5,
    payoutRatio: 45.0,
    frequency: "Quarterly",
    historySparkline: [40, 50, 60, 80, 90, 100],
    marketCap: "125.1B",
    pAffo: "7.1x",
    exDivDate: "Jan 09, 2025",
    payDate: "Feb 01, 2025",
    divType: "Qualified",
    safetyScore: 78,
    safetyLabel: "Safe",
    whyPick: "After the WarnerMedia spin-off, AT&T's dividend is reset and highly covered by its core wireless and fiber operations.",
    rank: "14",
    dividendGrowthHistory: [
      { year: 2021, payout: 2.08 },
      { year: 2022, payout: 1.11 },
      { year: 2023, payout: 1.11 }
    ]
  },
  {
    symbol: "WPC",
    name: "W.P. Carey",
    sector: "Real Estate",
    price: 62.40,
    yield: 6.20,
    growth5y: 1.2,
    payoutRatio: 82.0,
    frequency: "Quarterly",
    historySparkline: [40, 50, 60, 70, 85, 100],
    marketCap: "13.6B",
    pAffo: "12.5x",
    exDivDate: "Dec 28, 2024",
    payDate: "Jan 15, 2025",
    divType: "Qualified",
    safetyScore: 80,
    safetyLabel: "Safe",
    whyPick: "Diversified net-lease REIT with built-in rent escalators tied directly to inflation.",
    rank: "15",
    dividendGrowthHistory: [
      { year: 2021, payout: 4.19 },
      { year: 2022, payout: 4.23 },
      { year: 2023, payout: 4.27 }
    ]
  },
  {
    symbol: "JEPI",
    name: "JPMorgan Equity Premium ETF",
    sector: "Financials",
    price: 55.60,
    yield: 7.50,
    growth5y: 0.0,
    payoutRatio: 100.0,
    frequency: "Monthly",
    historySparkline: [60, 70, 65, 80, 90, 100],
    marketCap: "32.1B",
    pAffo: "N/A",
    exDivDate: "Dec 01, 2024",
    payDate: "Dec 05, 2024",
    divType: "Ordinary",
    safetyScore: 85,
    safetyLabel: "Very Safe",
    whyPick: "Actively managed covered call ETF offering high monthly income with lower volatility than the S&P 500.",
    rank: "16",
    dividendGrowthHistory: [
      { year: 2021, payout: 4.25 },
      { year: 2022, payout: 6.36 },
      { year: 2023, payout: 4.80 }
    ]
  },
  {
    symbol: "OKE",
    name: "ONEOK, Inc.",
    sector: "Energy",
    price: 78.50,
    yield: 5.50,
    growth5y: 6.8,
    payoutRatio: 65.0,
    frequency: "Quarterly",
    historySparkline: [30, 40, 60, 75, 90, 100],
    marketCap: "45.8B",
    pAffo: "14.2x",
    exDivDate: "Jan 25, 2025",
    payDate: "Feb 14, 2025",
    divType: "Qualified",
    safetyScore: 82,
    safetyLabel: "Safe",
    whyPick: "Natural gas pipeline operator with highly predictable fee-based earnings supporting strong dividend growth.",
    rank: "17",
    dividendGrowthHistory: [
      { year: 2021, payout: 3.74 },
      { year: 2022, payout: 3.74 },
      { year: 2023, payout: 3.82 }
    ]
  },
  {
    symbol: "USDC",
    name: "USD Coin Yield (USDC)",
    sector: "Stablecoins",
    price: 1.00,
    yield: 5.20,
    growth5y: 0.0,
    payoutRatio: 0,
    frequency: "Monthly",
    historySparkline: [100, 100, 100, 100, 100, 100],
    marketCap: "34.2B",
    pAffo: "N/A",
    exDivDate: "Nov 01, 2024",
    payDate: "Nov 30, 2024",
    divType: "Lending Interest",
    safetyScore: 95,
    safetyLabel: "Very Safe",
    whyPick: "Highly defensive dollar-pegged liquidity pool yield with full cash and short-term US Treasury reserves.",
    rank: "01",
    assetType: "Crypto",
    dividendGrowthHistory: [
      { year: 2020, payout: 0.05 },
      { year: 2021, payout: 0.05 },
      { year: 2022, payout: 0.05 },
      { year: 2023, payout: 0.05 }
    ]
  },
  {
    symbol: "SOL",
    name: "Solana Staking (SOL)",
    sector: "Crypto Staking",
    price: 148.50,
    yield: 6.40,
    growth5y: 24.5,
    payoutRatio: 5.0,
    frequency: "Monthly",
    historySparkline: [10, 25, 45, 60, 80, 100],
    marketCap: "69.1B",
    pAffo: "N/A",
    exDivDate: "Nov 01, 2024",
    payDate: "Nov 30, 2024",
    divType: "Staking Reward",
    safetyScore: 78,
    safetyLabel: "Safe",
    whyPick: "High network velocity and transactions fuel a robust staking return, balanced by moderate protocol emissions.",
    rank: "02",
    assetType: "Crypto",
    dividendGrowthHistory: [
      { year: 2020, payout: 4.2 },
      { year: 2021, payout: 5.5 },
      { year: 2022, payout: 6.8 },
      { year: 2023, payout: 9.5 }
    ]
  },
  {
    symbol: "ETH",
    name: "Ethereum Staking (ETH)",
    sector: "Crypto Staking",
    price: 3420.00,
    yield: 3.80,
    growth5y: 18.2,
    payoutRatio: 2.0,
    frequency: "Monthly",
    historySparkline: [25, 40, 50, 75, 90, 100],
    marketCap: "410.8B",
    pAffo: "N/A",
    exDivDate: "Nov 01, 2024",
    payDate: "Nov 30, 2024",
    divType: "Staking Reward",
    safetyScore: 88,
    safetyLabel: "Very Safe",
    whyPick: "The gold standard of decentralized yield, powered by continuous transaction fee burning and consensus rewards.",
    rank: "03",
    assetType: "Crypto",
    dividendGrowthHistory: [
      { year: 2020, payout: 80.5 },
      { year: 2021, payout: 95.0 },
      { year: 2022, payout: 110.2 },
      { year: 2023, payout: 130.0 }
    ]
  },
  {
    symbol: "DOT",
    name: "Polkadot Staking (DOT)",
    sector: "Crypto Staking",
    price: 6.25,
    yield: 11.80,
    growth5y: 1.5,
    payoutRatio: 10.0,
    frequency: "Monthly",
    historySparkline: [60, 50, 45, 70, 85, 100],
    marketCap: "8.9B",
    pAffo: "N/A",
    exDivDate: "Nov 01, 2024",
    payDate: "Nov 30, 2024",
    divType: "Staking Reward",
    safetyScore: 62,
    safetyLabel: "Safe",
    whyPick: "High nominal staking rewards to encourage network validation security, offset by a higher native token dilution rate.",
    rank: "04",
    assetType: "Crypto",
    dividendGrowthHistory: [
      { year: 2020, payout: 0.50 },
      { year: 2021, payout: 0.62 },
      { year: 2022, payout: 0.70 },
      { year: 2023, payout: 0.74 }
    ]
  },
  {
    symbol: "USDT",
    name: "Tether Yield (USDT)",
    sector: "Stablecoins",
    price: 1.00,
    yield: 5.50,
    growth5y: 0.0,
    payoutRatio: 0,
    frequency: "Monthly",
    historySparkline: [100, 100, 100, 100, 100, 100],
    marketCap: "112.5B",
    pAffo: "N/A",
    exDivDate: "Nov 01, 2024",
    payDate: "Nov 30, 2024",
    divType: "Lending Interest",
    safetyScore: 82,
    safetyLabel: "Safe",
    whyPick: "Consistent, high-liquidity lending interest across top-tier money markets, backed by commercial paper and treasury reserves.",
    rank: "05",
    assetType: "Crypto",
    dividendGrowthHistory: [
      { year: 2020, payout: 0.05 },
      { year: 2021, payout: 0.05 },
      { year: 2022, payout: 0.05 },
      { year: 2023, payout: 0.05 }
    ]
  },
  {
    symbol: "ADA",
    name: "Cardano Staking (ADA)",
    sector: "Crypto Staking",
    price: 0.45,
    yield: 3.50,
    growth5y: 5.0,
    payoutRatio: 5.0,
    frequency: "Continuous",
    historySparkline: [20, 30, 40, 60, 80, 100],
    marketCap: "15.8B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Staking Reward",
    safetyScore: 75,
    safetyLabel: "Safe",
    whyPick: "High scientific rigor and academic peer-reviewed protocol with steady, reliable staking mechanics without lockups.",
    rank: "06",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0.05 }, { year: 2022, payout: 0.05 }, { year: 2023, payout: 0.05 } ]
  },
  {
    symbol: "AVAX",
    name: "Avalanche Staking (AVAX)",
    sector: "Crypto Staking",
    price: 35.20,
    yield: 8.20,
    growth5y: 15.0,
    payoutRatio: 8.0,
    frequency: "Continuous",
    historySparkline: [10, 20, 45, 70, 90, 100],
    marketCap: "13.2B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Staking Reward",
    safetyScore: 72,
    safetyLabel: "Safe",
    whyPick: "Highly scalable subnets and strong institutional adoption drive lucrative native validation yields.",
    rank: "07",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 2.1 }, { year: 2022, payout: 3.5 }, { year: 2023, payout: 4.8 } ]
  },
  {
    symbol: "MATIC",
    name: "Polygon Staking (MATIC)",
    sector: "Crypto Staking",
    price: 0.75,
    yield: 5.10,
    growth5y: 12.0,
    payoutRatio: 10.0,
    frequency: "Continuous",
    historySparkline: [30, 40, 55, 65, 85, 100],
    marketCap: "7.5B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Staking Reward",
    safetyScore: 80,
    safetyLabel: "Safe",
    whyPick: "Leading Ethereum layer-2 scaling solution with massive enterprise partnerships and steady reward emissions.",
    rank: "08",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0.03 }, { year: 2022, payout: 0.04 }, { year: 2023, payout: 0.05 } ]
  },
  {
    symbol: "LINK",
    name: "Chainlink Staking (LINK)",
    sector: "Crypto Staking",
    price: 14.50,
    yield: 4.50,
    growth5y: 8.0,
    payoutRatio: 5.0,
    frequency: "Continuous",
    historySparkline: [40, 50, 60, 75, 85, 100],
    marketCap: "8.5B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Staking Reward",
    safetyScore: 85,
    safetyLabel: "Very Safe",
    whyPick: "Crucial oracle infrastructure for the entire DeFi ecosystem, offering highly secure yields to node operators and delegators.",
    rank: "09",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0.2 }, { year: 2022, payout: 0.4 }, { year: 2023, payout: 0.6 } ]
  },
  {
    symbol: "ATOM",
    name: "Cosmos Staking (ATOM)",
    sector: "Crypto Staking",
    price: 8.20,
    yield: 14.50,
    growth5y: 2.0,
    payoutRatio: 15.0,
    frequency: "Continuous",
    historySparkline: [60, 50, 55, 70, 85, 100],
    marketCap: "3.2B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Staking Reward",
    safetyScore: 65,
    safetyLabel: "Safe",
    whyPick: "High inflation rate drives massive nominal yields, but real yield requires careful attention to tokenomics.",
    rank: "10",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 1.1 }, { year: 2022, payout: 1.2 }, { year: 2023, payout: 1.4 } ]
  },
  {
    symbol: "TRX",
    name: "Tron Staking (TRX)",
    sector: "Crypto Staking",
    price: 0.12,
    yield: 4.20,
    growth5y: 6.0,
    payoutRatio: 0,
    frequency: "Continuous",
    historySparkline: [40, 50, 60, 75, 90, 100],
    marketCap: "10.5B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Staking Reward",
    safetyScore: 78,
    safetyLabel: "Safe",
    whyPick: "Deflationary tokenomics due to massive fee burning from USDT transfers provides a sustainable real yield.",
    rank: "11",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0.003 }, { year: 2022, payout: 0.004 }, { year: 2023, payout: 0.005 } ]
  },
  {
    symbol: "BNB",
    name: "Binance Coin Yield (BNB)",
    sector: "DeFi Lending",
    price: 590.00,
    yield: 2.50,
    growth5y: 20.0,
    payoutRatio: 0,
    frequency: "Continuous",
    historySparkline: [30, 50, 60, 80, 95, 100],
    marketCap: "88.5B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Lending Interest",
    safetyScore: 82,
    safetyLabel: "Safe",
    whyPick: "Supported by the largest crypto exchange globally with consistent token burns driving scarcity and value.",
    rank: "12",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 8.0 }, { year: 2022, payout: 10.0 }, { year: 2023, payout: 14.0 } ]
  },
  {
    symbol: "DAI",
    name: "Dai Savings Rate (DAI)",
    sector: "Stablecoins",
    price: 1.00,
    yield: 5.00,
    growth5y: 0.0,
    payoutRatio: 0,
    frequency: "Continuous",
    historySparkline: [100, 100, 100, 100, 100, 100],
    marketCap: "5.2B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Protocol Yield",
    safetyScore: 92,
    safetyLabel: "Very Safe",
    whyPick: "The premier decentralized stablecoin backed by overcollateralized assets offering risk-free equivalent yields in DeFi.",
    rank: "13",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0.05 }, { year: 2022, payout: 0.05 }, { year: 2023, payout: 0.05 } ]
  },
  {
    symbol: "UNI",
    name: "Uniswap LP Fees (UNI)",
    sector: "DeFi Protocol",
    price: 10.50,
    yield: 12.50,
    growth5y: 10.0,
    payoutRatio: 100,
    frequency: "Continuous",
    historySparkline: [40, 55, 50, 70, 85, 100],
    marketCap: "6.3B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Liquidity Fees",
    safetyScore: 68,
    safetyLabel: "Safe",
    whyPick: "Dominant decentralized exchange generating massive trading fees for liquidity providers, though subject to impermanent loss.",
    rank: "14",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 1.2 }, { year: 2022, payout: 1.5 }, { year: 2023, payout: 1.8 } ]
  },
  {
    symbol: "AAVE",
    name: "Aave Lending (AAVE)",
    sector: "DeFi Lending",
    price: 115.00,
    yield: 4.80,
    growth5y: 8.5,
    payoutRatio: 100,
    frequency: "Continuous",
    historySparkline: [50, 60, 55, 75, 85, 100],
    marketCap: "1.7B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Lending Interest",
    safetyScore: 85,
    safetyLabel: "Very Safe",
    whyPick: "Blue-chip DeFi money market protocol with robust safety modules and audited smart contracts providing stable lending yields.",
    rank: "15",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 4.5 }, { year: 2022, payout: 5.0 }, { year: 2023, payout: 5.5 } ]
  },
  {
    symbol: "MKR",
    name: "MakerDAO Burn (MKR)",
    sector: "DeFi Protocol",
    price: 2800.00,
    yield: 3.50,
    growth5y: 12.0,
    payoutRatio: 0,
    frequency: "Continuous",
    historySparkline: [60, 50, 70, 85, 90, 100],
    marketCap: "2.6B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Token Buyback",
    safetyScore: 88,
    safetyLabel: "Very Safe",
    whyPick: "Protocol profits are used to buy and burn MKR tokens, providing a silent, tax-efficient yield mechanism to holders.",
    rank: "16",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 50 }, { year: 2022, payout: 80 }, { year: 2023, payout: 120 } ]
  },
  {
    symbol: "SNX",
    name: "Synthetix Staking (SNX)",
    sector: "DeFi Protocol",
    price: 2.80,
    yield: 22.50,
    growth5y: 1.0,
    payoutRatio: 50,
    frequency: "Weekly",
    historySparkline: [80, 60, 50, 70, 85, 100],
    marketCap: "0.9B",
    pAffo: "N/A",
    exDivDate: "Weekly",
    payDate: "Weekly",
    divType: "Staking Reward",
    safetyScore: 55,
    safetyLabel: "Borderline",
    whyPick: "Extremely high yield derived from trading fees and inflationary rewards, but requires active management to maintain collateral ratios.",
    rank: "17",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0.8 }, { year: 2022, payout: 0.5 }, { year: 2023, payout: 0.6 } ]
  },
  {
    symbol: "CRV",
    name: "Curve Finance (CRV)",
    sector: "DeFi Protocol",
    price: 0.45,
    yield: 15.00,
    growth5y: -5.0,
    payoutRatio: 100,
    frequency: "Continuous",
    historySparkline: [90, 70, 50, 60, 80, 100],
    marketCap: "0.5B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Trading Fees",
    safetyScore: 60,
    safetyLabel: "Borderline",
    whyPick: "The backbone of DeFi stablecoin trading, distributing real admin fees to lockers (veCRV), though token emissions apply pressure.",
    rank: "18",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0.15 }, { year: 2022, payout: 0.08 }, { year: 2023, payout: 0.07 } ]
  },
  {
    symbol: "NEAR",
    name: "NEAR Protocol (NEAR)",
    sector: "Crypto Staking",
    price: 6.80,
    yield: 8.50,
    growth5y: 14.0,
    payoutRatio: 5.0,
    frequency: "Continuous",
    historySparkline: [20, 30, 50, 70, 85, 100],
    marketCap: "7.2B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Staking Reward",
    safetyScore: 74,
    safetyLabel: "Safe",
    whyPick: "Sharded proof-of-stake blockchain with excellent UX, providing solid validator yields to secure the network.",
    rank: "19",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0.4 }, { year: 2022, payout: 0.5 }, { year: 2023, payout: 0.7 } ]
  },
  {
    symbol: "FTM",
    name: "Fantom Staking (FTM)",
    sector: "Crypto Staking",
    price: 0.85,
    yield: 4.80,
    growth5y: 5.0,
    payoutRatio: 4.0,
    frequency: "Continuous",
    historySparkline: [30, 40, 50, 65, 80, 100],
    marketCap: "2.4B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Staking Reward",
    safetyScore: 68,
    safetyLabel: "Safe",
    whyPick: "High-speed DAG-based smart contract platform offering consistent delegation rewards with varying lock-up periods.",
    rank: "20",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0.03 }, { year: 2022, payout: 0.04 }, { year: 2023, payout: 0.04 } ]
  },
  {
    symbol: "XTZ",
    name: "Tezos Baking (XTZ)",
    sector: "Crypto Staking",
    price: 1.15,
    yield: 5.50,
    growth5y: 1.0,
    payoutRatio: 5.0,
    frequency: "Continuous",
    historySparkline: [50, 45, 55, 70, 85, 100],
    marketCap: "1.1B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Staking Reward",
    safetyScore: 78,
    safetyLabel: "Safe",
    whyPick: "One of the original liquid proof-of-stake networks with completely non-custodial 'baking' rewards and self-amendment.",
    rank: "21",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0.05 }, { year: 2022, payout: 0.06 }, { year: 2023, payout: 0.06 } ]
  },
  {
    symbol: "ALGO",
    name: "Algorand Governance (ALGO)",
    sector: "Crypto Staking",
    price: 0.22,
    yield: 6.20,
    growth5y: -4.0,
    payoutRatio: 0,
    frequency: "Quarterly",
    historySparkline: [80, 60, 40, 55, 75, 100],
    marketCap: "1.8B",
    pAffo: "N/A",
    exDivDate: "Quarterly",
    payDate: "Quarterly",
    divType: "Governance Reward",
    safetyScore: 70,
    safetyLabel: "Safe",
    whyPick: "Yield is derived from committing tokens to protocol governance and participating in voting sessions quarterly.",
    rank: "22",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0.01 }, { year: 2022, payout: 0.012 }, { year: 2023, payout: 0.015 } ]
  },
  {
    symbol: "EGLD",
    name: "MultiversX Staking (EGLD)",
    sector: "Crypto Staking",
    price: 45.00,
    yield: 8.00,
    growth5y: 2.0,
    payoutRatio: 10.0,
    frequency: "Continuous",
    historySparkline: [40, 35, 50, 65, 85, 100],
    marketCap: "1.2B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Staking Reward",
    safetyScore: 66,
    safetyLabel: "Safe",
    whyPick: "High-throughput blockchain network providing robust delegation yields to secure its distinct sharding architecture.",
    rank: "23",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 2.5 }, { year: 2022, payout: 3.2 }, { year: 2023, payout: 3.6 } ]
  },
  {
    symbol: "KAVA",
    name: "Kava Staking (KAVA)",
    sector: "DeFi Protocol",
    price: 0.85,
    yield: 15.50,
    growth5y: -2.0,
    payoutRatio: 20.0,
    frequency: "Continuous",
    historySparkline: [70, 50, 45, 60, 80, 100],
    marketCap: "0.8B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Staking Reward",
    safetyScore: 58,
    safetyLabel: "Borderline",
    whyPick: "Cosmos-based DeFi hub offering massive yields, offset by aggressive token inflation mechanics.",
    rank: "24",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0.1 }, { year: 2022, payout: 0.12 }, { year: 2023, payout: 0.14 } ]
  },
  {
    symbol: "LDO",
    name: "Lido DAO (LDO)",
    sector: "Liquid Staking",
    price: 2.15,
    yield: 0.00,
    growth5y: 15.0,
    payoutRatio: 0,
    frequency: "Continuous",
    historySparkline: [20, 30, 50, 70, 85, 100],
    marketCap: "1.9B",
    pAffo: "N/A",
    exDivDate: "N/A",
    payDate: "N/A",
    divType: "Governance Asset",
    safetyScore: 82,
    safetyLabel: "Safe",
    whyPick: "Not direct yield, but holding LDO governs the largest liquid staking derivative (stETH) market, capturing massive protocol revenue.",
    rank: "25",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0 }, { year: 2022, payout: 0 }, { year: 2023, payout: 0 } ]
  },
  {
    symbol: "RPL",
    name: "Rocket Pool (RPL)",
    sector: "Liquid Staking",
    price: 22.50,
    yield: 8.50,
    growth5y: 8.0,
    payoutRatio: 5.0,
    frequency: "Continuous",
    historySparkline: [40, 45, 60, 75, 90, 100],
    marketCap: "0.4B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Node Operator Reward",
    safetyScore: 76,
    safetyLabel: "Safe",
    whyPick: "Decentralized alternative to Lido where running a minipool generates outsized ETH and RPL rewards.",
    rank: "26",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 1.2 }, { year: 2022, payout: 1.5 }, { year: 2023, payout: 1.8 } ]
  },
  {
    symbol: "MINA",
    name: "Mina Protocol (MINA)",
    sector: "Crypto Staking",
    price: 0.95,
    yield: 11.20,
    growth5y: 3.0,
    payoutRatio: 12.0,
    frequency: "Continuous",
    historySparkline: [60, 50, 40, 65, 80, 100],
    marketCap: "1.0B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Staking Reward",
    safetyScore: 68,
    safetyLabel: "Safe",
    whyPick: "Zero-knowledge lightweight blockchain offering double-digit staking returns to block producers and delegators.",
    rank: "27",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0.08 }, { year: 2022, payout: 0.1 }, { year: 2023, payout: 0.11 } ]
  },
  {
    symbol: "ICP",
    name: "Internet Computer (ICP)",
    sector: "Crypto Staking",
    price: 12.80,
    yield: 14.80,
    growth5y: -10.0,
    payoutRatio: 8.0,
    frequency: "Continuous",
    historySparkline: [90, 60, 40, 50, 70, 100],
    marketCap: "5.8B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Neuron Voting Reward",
    safetyScore: 64,
    safetyLabel: "Borderline",
    whyPick: "Unique 'Neuron' staking mechanism locks tokens for up to 8 years, paying out massive rewards for governance participation.",
    rank: "28",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 1.5 }, { year: 2022, payout: 1.7 }, { year: 2023, payout: 1.9 } ]
  },
  {
    symbol: "FIL",
    name: "Filecoin (FIL)",
    sector: "DeFi Protocol",
    price: 6.20,
    yield: 18.00,
    growth5y: -5.0,
    payoutRatio: 15.0,
    frequency: "Continuous",
    historySparkline: [80, 60, 45, 55, 75, 100],
    marketCap: "3.2B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Storage Mining Reward",
    safetyScore: 55,
    safetyLabel: "Borderline",
    whyPick: "Storage providers earn high yields by committing capacity, but delegators also benefit from DeFi lending markets on the FVM.",
    rank: "29",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0.8 }, { year: 2022, payout: 1.0 }, { year: 2023, payout: 1.2 } ]
  },
  {
    symbol: "STX",
    name: "Stacks (STX)",
    sector: "Crypto Staking",
    price: 2.80,
    yield: 7.50,
    growth5y: 22.0,
    payoutRatio: 0,
    frequency: "Continuous",
    historySparkline: [20, 30, 45, 65, 85, 100],
    marketCap: "4.0B",
    pAffo: "N/A",
    exDivDate: "Daily",
    payDate: "Daily",
    divType: "Bitcoin Yield",
    safetyScore: 84,
    safetyLabel: "Safe",
    whyPick: "Unique 'Stacking' mechanism where locking STX earns native, non-inflationary Bitcoin (BTC) as a yield reward.",
    rank: "30",
    assetType: "Crypto",
    dividendGrowthHistory: [ { year: 2021, payout: 0.15 }, { year: 2022, payout: 0.2 }, { year: 2023, payout: 0.25 } ]
  },
  // --- International Dividend Assets ---
  {
    symbol: "BHP",
    name: "BHP Group Ltd",
    sector: "Basic Materials",
    price: 58.20,
    yield: 5.40,
    growth5y: 6.2,
    payoutRatio: 65.0,
    frequency: "Annual",
    historySparkline: [50, 70, 80, 60, 90, 100],
    marketCap: "145.2B",
    pAffo: "11.5x",
    exDivDate: "Sep 07, 2024",
    payDate: "Sep 28, 2024",
    divType: "Qualified",
    safetyScore: 82,
    safetyLabel: "Safe",
    whyPick: "World's largest mining company with incredible free cash flow from iron ore and copper, distributing strong dividends.",
    dividendGrowthHistory: [
      { year: 2018, payout: 1.18 },
      { year: 2019, payout: 1.33 },
      { year: 2020, payout: 1.20 },
      { year: 2021, payout: 3.01 },
      { year: 2022, payout: 3.25 },
      { year: 2023, payout: 1.70 }
    ],
    assetType: "Stock",
    country: "AU",
    exchange: "ASX"
  },
  {
    symbol: "ULVR",
    name: "Unilever PLC",
    sector: "Consumer Staples",
    price: 48.50,
    yield: 3.80,
    growth5y: 4.5,
    payoutRatio: 58.2,
    frequency: "Quarterly",
    historySparkline: [40, 50, 60, 75, 85, 100],
    marketCap: "122.1B",
    pAffo: "16.2x",
    exDivDate: "Nov 02, 2024",
    payDate: "Dec 05, 2024",
    divType: "Qualified",
    safetyScore: 94,
    safetyLabel: "Very Safe",
    whyPick: "Global consumer goods giant with a deep moat and reliable compounding dividend history across economic cycles.",
    dividendGrowthHistory: [
      { year: 2018, payout: 1.55 },
      { year: 2019, payout: 1.64 },
      { year: 2020, payout: 1.64 },
      { year: 2021, payout: 1.70 },
      { year: 2022, payout: 1.75 },
      { year: 2023, payout: 1.82 }
    ],
    assetType: "Stock",
    country: "UK",
    exchange: "LSE"
  },
  {
    symbol: "RY",
    name: "Royal Bank of Canada",
    sector: "Financials",
    price: 98.40,
    yield: 4.25,
    growth5y: 7.1,
    payoutRatio: 48.0,
    frequency: "Quarterly",
    historySparkline: [30, 45, 60, 75, 80, 100],
    marketCap: "135.5B",
    pAffo: "12.1x",
    exDivDate: "Jan 25, 2025",
    payDate: "Feb 24, 2025",
    divType: "Qualified",
    safetyScore: 89,
    safetyLabel: "Safe",
    whyPick: "Canada's largest bank with highly regulated, oligopoly-like advantages and a stellar dividend growth track record.",
    dividendGrowthHistory: [
      { year: 2018, payout: 3.80 },
      { year: 2019, payout: 4.08 },
      { year: 2020, payout: 4.32 },
      { year: 2021, payout: 4.32 },
      { year: 2022, payout: 4.96 },
      { year: 2023, payout: 5.32 }
    ],
    assetType: "Stock",
    country: "CA",
    exchange: "TSX"
  },
  {
    symbol: "SAN",
    name: "Sanofi",
    sector: "Healthcare",
    price: 52.10,
    yield: 4.10,
    growth5y: 3.5,
    payoutRatio: 55.4,
    frequency: "Annual",
    historySparkline: [60, 50, 70, 80, 90, 100],
    marketCap: "130.4B",
    pAffo: "14.3x",
    exDivDate: "May 15, 2025",
    payDate: "Jun 01, 2025",
    divType: "Qualified",
    safetyScore: 88,
    safetyLabel: "Safe",
    whyPick: "Major European pharmaceutical leader with strong pipeline and consistently rising annual dividends.",
    dividendGrowthHistory: [
      { year: 2018, payout: 3.07 },
      { year: 2019, payout: 3.15 },
      { year: 2020, payout: 3.20 },
      { year: 2021, payout: 3.33 },
      { year: 2022, payout: 3.56 },
      { year: 2023, payout: 3.76 }
    ],
    assetType: "Stock",
    country: "FR",
    exchange: "Euronext"
  }
];

export const initialTransactions: Transaction[] = [
  {
    id: "tx-1",
    type: "Dividend",
    asset: "AAPL",
    date: "Today, 10:42 AM",
    amount: 142.50,
    isIncome: true
  },
  {
    id: "tx-2",
    type: "Buy",
    asset: "SCHD",
    date: "Yesterday, 4:15 PM",
    amount: 2000.00,
    isIncome: false
  },
  {
    id: "tx-3",
    type: "Dividend",
    asset: "KO",
    date: "Oct 24, 2023",
    amount: 88.20,
    isIncome: true
  },
  {
    id: "tx-4",
    type: "Dividend",
    asset: "O",
    date: "Oct 22, 2023",
    amount: 42.12,
    isIncome: true
  }
];

export const initialPayouts: Payout[] = [
  {
    ticker: "MSFT",
    amount: 342.10,
    exDate: "Nov 15, 2023",
    payDate: "Dec 12, 2023",
    status: "Upcoming"
  },
  {
    ticker: "JPM",
    amount: 182.00,
    exDate: "Nov 02, 2023",
    payDate: "Nov 30, 2023",
    status: "Confirmed"
  },
  {
    ticker: "ABBV",
    amount: 510.45,
    exDate: "Oct 12, 2023",
    payDate: "Nov 15, 2023",
    status: "Confirmed"
  }
];

export const initialSettings: UserSettings = {
  name: "Alexander Sterling",
  email: "alex.sterling@example.com",
  avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuACO7n1rnf8gTzl7lt0t0gpg_bd8zy6lu3lM4v3aDfkqCvX6SxrsVHqtFAFfBC_uqqcugumb8zPvVRALo7G2tt85cn9-fh_kAfBdbDTrpfkIRb1UNfBFq4vvaRm59NlkM-VEvoncbXNIiZzmWEJu7O3YRaoCO20ffsByRpA9-_e_NUZgHl8Unx9C2PBHGlLA7qRKXtywF81-NpACUIuaAoeGrtcrwEwcwsbKlaeQmQDRcOJ1EbFfdWFGA",
  pushNotifications: true,
  emailAlerts: true,
  weeklyReports: false,
  compactView: false,
  biometricUnlock: true,
  isPro: true,
  portfolioBudget: 10000,
  currency: "USD"
};
